## Purpose: Neural Network construction starting from Perceptron to layered architecture

## 1) Without using Numpy

### a) Single Neuron

In [96]:
# To display the single neuron to be constructed
from IPython.display import Image
Image(url="./images/single_neuron.png", width=400, height=400)

In [97]:
inputs  = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

In [98]:
output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias

In [99]:
print("Result of the Single Neuron")
print(output)

Result of the Single Neuron
4.8


### b) Layer of neurons

#### First way
Here each weights are written seperately in each variables

In [100]:
inputs = [ 1 , 2 , 3 , 2.5 ]
weights1 = [ 0.2 , 0.8 , -0.5 , 1 ]
weights2 = [ 0.5 , -0.91 , 0.26 , -0.5 ]
weights3 = [ -0.26 , -0.27 , 0.17 , 0.87 ]
bias1 = 2
bias2 = 3
bias3 = 0.5

outputs = [
	# Neuron 1:
	inputs[ 0 ] * weights1[ 0 ] +
	inputs[ 1 ] * weights1[ 1 ] +
	inputs[ 2 ] * weights1[ 2 ] +
	inputs[ 3 ] * weights1[ 3 ] +
	bias1,
	
	# Neuron 2:
	inputs[ 0 ] * weights2[ 0 ] +
	inputs[ 1 ] * weights2[ 1 ] +
	inputs[ 2 ] * weights2[ 2 ] +
	inputs[ 3 ] * weights2[ 3 ] +
	bias2,
	
	# Neuron 3:
	inputs[ 0 ] * weights3[ 0 ] +
	inputs[ 1 ] * weights3[ 1 ] +
	inputs[ 2 ] * weights3[ 2 ] +
	inputs[ 3 ] * weights3[ 3 ] +
	bias3
	]
print("Result of the Output Layer")
print (outputs)

Result of the Output Layer
[4.8, 1.21, 2.385]


#### Second way
Here weights in form of list of lists way where list-1 is weight-1, etc

In [101]:
inputs = [ 1 , 2 , 3 , 2.5 ]
weights = [[0.2, 0.8, -0.5, 1], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87] ]
biases = [ 2 , 3 , 0.5 ]

In [102]:
# Output of current layer
layer_outputs = []

In [103]:
# For each neuron
for neuron_weights, neuron_bias in zip(weights, biases):
    # zero the output of the given neuron
    neuron_output = 0
    for n_input, weight in zip(inputs, neuron_weights):
        # Multiply the input and associated weight and add to neuron_output
        neuron_output += n_input*weight
    neuron_output += neuron_bias
    # Append the neuron output to the Layer output
    layer_outputs.append(neuron_output)

print("Result of the Output Layer")
print(layer_outputs)

Result of the Output Layer
[4.8, 1.21, 2.385]


## Using Numpy

### a) Single Neuron

In [104]:
import numpy as np

inputs = [ 1.0 , 2.0 , 3.0 , 2.5 ]
weights = [ 0.2 , 0.8 , -0.5 , 1.0 ]
bias = 2.0

outputs = np.dot(inputs, weights) + bias

print("Result of Single Neuron")
print (outputs)

Result of Single Neuron
4.8


### b) Input Layer and Multiple output neurons

In [105]:
# To display the single neuron to be constructed
print("We shall be implementing the below Figure")

from IPython.display import Image
Image(url="./images/input_output1.png", width=600, height=600)

We shall be implementing the below Figure


In [106]:
import numpy as np

inputs = [ 1.0 , 2.0 , 3.0 , 4.0 ]
weights = [[ 0.2 , 0.8 , -0.5 , 1 ],[ 0.5 , -0.91 , 0.26 , -0.5 ],[ -0.26 , -0.27 , 0.17 , 0.87 ]]
biases = [ 2.0 , 3.0 , 0.5 ]

layer_outputs = np.dot(inputs, np.array(weights).T) + biases
print("The Result of output layer")
print (layer_outputs)

The Result of output layer
[6.3  0.46 3.69]


In [107]:
inputs = [ 1.0 , 2.0 , 3.0 , 2.5 ]
np.dot(inputs, np.array(weights).T)

array([ 2.8  , -1.79 ,  1.885])

### c) Input batch and Multiple output neuron

In [108]:
# To display the single neuron to be constructed
print("We shall be implementing the below Figure")
from IPython.display import Image
Image(url="./images/input_output2.png", width=600, height=600)

We shall be implementing the below Figure


In [109]:
import numpy as np
inputs = [[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0],[9.0, 10.0, 11.0, 12.0]]
weights = [[ 0.2 , 0.8 , -0.5 , 1 ],[ 0.5 , -0.91 , 0.26 , -0.5 ],[ -0.26 , -0.27 , 0.17 , 0.87 ]]
biases = [ 2.0 , 3.0 , 0.5 ]

print("** inputs shape = ", np.array(inputs).shape)
print(f"Here, \n{np.array(inputs).shape[0]} are number of batches and \n{np.array(inputs).shape[1]} are number of inputs in one batch\n ")

print("** weights shape = ", np.array(weights).shape)
print(f"Here,\n{np.array(weights).shape[0]} are number of output nodes and \n{np.array(weights).shape[1]} are number of weights associated to one output node (i.e. it is equal to number of input in one batch)\n")

print("Hence, in order to multiply we need to Transpose weight matrix. \n")

layer_output = np.dot(inputs, np.array(weights).T) + biases

print("** layer_output.shape = ", layer_output.shape)
print(f"where, \n{layer_output.shape[0]} indicates number of generated output batches (i.e. it is equal to number of input batches) and\n{layer_output.shape[1]} are number of output for one input batch from output layer\n")
print("** layer_output = ", layer_output)

** inputs shape =  (3, 4)
Here, 
3 are number of batches and 
4 are number of inputs in one batch
 
** weights shape =  (3, 4)
Here,
3 are number of output nodes and 
4 are number of weights associated to one output node (i.e. it is equal to number of input in one batch)

Hence, in order to multiply we need to Transpose weight matrix. 

** layer_output.shape =  (3, 3)
where, 
3 indicates number of generated output batches (i.e. it is equal to number of input batches) and
3 are number of output for one input batch from output layer

** layer_output =  [[ 6.3   0.46  3.69]
 [12.3  -2.14  5.73]
 [18.3  -4.74  7.77]]


### Adding Hidden layers

In [110]:
# To display the single neuron to be constructed
print("We shall be implementing the below Figure")
from IPython.display import Image
Image(url="./images/input_hidden_output1.png", width=750, height=750)

We shall be implementing the below Figure


In [111]:
import numpy as np

inputs = [[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0],[9.0, 10.0, 11.0, 12.0]]

# Hidden Layer-1
weights1 = [[ 0.2 , 0.8 , -0.5 , 1 ],[ 0.5 , -0.91 , 0.26 , -0.5 ],[ -0.26 , -0.27 , 0.17 , 0.87 ]]
biases1 = [ 2.0 , 3.0 , 0.5 ]

# Output Layer
weights2 = [[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]]
biases2  = [1.0 , 2.0]

hidden_layer = np.dot(inputs, np.array(weights1).T) +biases1
output_layer = np.dot(hidden_layer, np.array(weights2).T) +biases2

print("* inputs shape = ", np.array(inputs).shape)
print("* weights1 shape = ", np.array(weights).shape, "\n")
print("** hidden_layer shape = ", np.array(hidden_layer).shape)
print(f"where, \n{hidden_layer.shape[0]} indicates number of generated hidden batches (i.e. it is equal to number of input batches) and\n{hidden_layer.shape[1]} are number of output for one input batch from hidden layer")
print("** weights2 shape = ", np.array(weights2).shape, "\n")
print("*** output_layer shape = ", np.array(output_layer).shape)
print("output_layer = ", output_layer)

* inputs shape =  (3, 4)
* weights1 shape =  (3, 4) 

** hidden_layer shape =  (3, 3)
where, 
3 indicates number of generated hidden batches (i.e. it is equal to number of input batches) and
3 are number of output for one input batch from hidden layer
** weights2 shape =  (2, 3) 

*** output_layer shape =  (3, 2)
output_layer =  [[ 2.829  6.964]
 [ 3.521  9.288]
 [ 4.213 11.612]]
